# Generated by Django 4.0.5 on 2022-07-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_newscategory_category_image_news_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name_plural': 'News Categories'},
        ),
    ]
