# Generated by Django 4.0.5 on 2022-07-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('birthplace', models.CharField(choices=[('1', 'Chitwan'), ('2', 'Kathmandu'), ('3', 'Bhaktapur'), ('4', 'Lalitpur')], max_length=50)),
                ('citizenship_no', models.IntegerField()),
                ('issue_zone', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
            ],
        ),
    ]
