# Generated by Django 4.0.5 on 2022-07-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_idcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='issue_date',
        ),
    ]
