# Generated by Django 4.0.5 on 2022-11-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filesadmin',
            options={'verbose_name_plural': 'Files Uploads'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='idcard',
            options={'verbose_name_plural': 'Id Cards'},
        ),
        migrations.AlterField(
            model_name='idcard',
            name='birthplace',
            field=models.CharField(choices=[('Chitwan', 'Chitwan'), ('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur')], max_length=50),
        ),
    ]
